/**
 * Seed data for problem bank
 * Contains sample UniversalProblems with performance history
 */

import { UniversalProblem } from '../types/universalPayloads';

export const SEED_PROBLEMS: UniversalProblem[] = [
  {
    problemId: 'S1_P1',
    documentId: 'doc_seed_001',
    subject: 'Math',
    sectionId: 'S1',
    content: 'Solve for x: 2x + 5 = 13',
    cognitive: {
      bloomsLevel: 'Remember',
      bloomsConfidence: 0.95,
      bloomsReasoning: 'Direct recall of basic algebra operations',
      bloomsContextDependent: false,
      complexityLevel: 1,
      estimatedTimeMinutes: 1.0,
      timeBreakdown: {
        readingMinutes: 0.2,
        comprehensionMinutes: 0.2,
        computationMinutes: 0.4,
        reasoningMinutes: 0.1,
        writingMinutes: 0.1,
      },
      linguisticComplexity: 0.2,
      reasoningStepsRequired: 1,
      proceduralWeight: 0.8,
      noveltyScore: 0.1,
      estimatedGradeLevel: 6,
    },
    classification: {
      problemType: 'linear_equation',
      topics: ['algebra', 'linear_equations', 'one_variable'],
      requiresCalculator: false,
      requiresInterpretation: false,
      keywords: ['algebra', 'solving'],
    },
    structure: {
      isSubpart: false,
      numberingStyle: '1.',
      multiPartCount: 0,
      sourceLineStart: 1,
      sourceLineEnd: 1,
      type: 'short_answer',
    },
    analysis: {
      confidenceScore: 0.95,
      processedAt: new Date().toISOString(),
    },
  },
  {
    problemId: 'S1_P2',
    documentId: 'doc_seed_001',
    subject: 'Math',
    sectionId: 'S1',
    content: 'A researcher randomly selects 40 college students and measures their heights. What is the approximate shape of the sampling distribution of the sample mean?',
    cognitive: {
      bloomsLevel: 'Understand',
      bloomsConfidence: 0.88,
      bloomsReasoning: 'Question asks students to identify and describe based on Central Limit Theorem',
      bloomsContextDependent: true,
      complexityLevel: 2,
      estimatedTimeMinutes: 2.5,
      timeBreakdown: {
        readingMinutes: 0.4,
        comprehensionMinutes: 0.8,
        computationMinutes: 0.0,
        reasoningMinutes: 1.0,
        writingMinutes: 0.3,
      },
      linguisticComplexity: 0.52,
      reasoningStepsRequired: 2,
      proceduralWeight: 0.2,
      noveltyScore: 0.35,
      estimatedGradeLevel: 11,
    },
    classification: {
      problemType: 'conceptual_identification',
      topics: ['sampling_distributions', 'central_limit_theorem', 'statistics'],
      requiresCalculator: false,
      requiresInterpretation: true,
      keywords: ['sampling', 'distribution', 'statistics'],
    },
    structure: {
      isSubpart: false,
      numberingStyle: '1.',
      multiPartCount: 0,
      sourceLineStart: 2,
      sourceLineEnd: 2,
      type: 'short_answer',
    },
    analysis: {
      confidenceScore: 0.82,
      processedAt: new Date().toISOString(),
    },
  },
  {
    problemId: 'S1_P3',
    documentId: 'doc_seed_001',
    subject: 'Math',
    sectionId: 'S1',
    content: 'Calculate the p-value for a hypothesis test where the test statistic is z = 2.15 (two-tailed test)',
    cognitive: {
      bloomsLevel: 'Apply',
      bloomsConfidence: 0.85,
      bloomsReasoning: 'Requires calculation using z-table or normal distribution',
      bloomsContextDependent: false,
      complexityLevel: 3,
      estimatedTimeMinutes: 3.0,
      timeBreakdown: {
        readingMinutes: 0.3,
        comprehensionMinutes: 0.5,
        computationMinutes: 1.5,
        reasoningMinutes: 0.5,
        writingMinutes: 0.2,
      },
      linguisticComplexity: 0.48,
      reasoningStepsRequired: 3,
      proceduralWeight: 0.7,
      noveltyScore: 0.25,
      estimatedGradeLevel: 12,
    },
    classification: {
      problemType: 'hypothesis_test_calculation',
      topics: ['hypothesis_testing', 'p_values', 'normal_distribution'],
      requiresCalculator: true,
      requiresInterpretation: true,
      keywords: ['hypothesis', 'p-value', 'statistics'],
    },
    structure: {
      isSubpart: false,
      numberingStyle: '1.',
      multiPartCount: 0,
      sourceLineStart: 3,
      sourceLineEnd: 3,
      type: 'short_answer',
    },
    analysis: {
      confidenceScore: 0.79,
      processedAt: new Date().toISOString(),
    },
  },
  {
    problemId: 'S2_P1',
    documentId: 'doc_seed_001',
    subject: 'Science',
    sectionId: 'S2',
    content: 'Explain why the greenhouse effect leads to climate change',
    cognitive: {
      bloomsLevel: 'Understand',
      bloomsConfidence: 0.82,
      bloomsReasoning: 'Requires explanation of causal relationships',
      bloomsContextDependent: true,
      complexityLevel: 2,
      estimatedTimeMinutes: 4.0,
      timeBreakdown: {
        readingMinutes: 0.3,
        comprehensionMinutes: 1.0,
        computationMinutes: 0.0,
        reasoningMinutes: 2.0,
        writingMinutes: 0.7,
      },
      linguisticComplexity: 0.65,
      reasoningStepsRequired: 4,
      proceduralWeight: 0.1,
      noveltyScore: 0.45,
      estimatedGradeLevel: 9,
    },
    classification: {
      problemType: 'short_answer_explanation',
      topics: ['climate_change', 'greenhouse_effect', 'earth_science'],
      requiresCalculator: false,
      requiresInterpretation: true,
      keywords: ['climate', 'greenhouse', 'environment'],
    },
    structure: {
      isSubpart: false,
      numberingStyle: '1.',
      multiPartCount: 0,
      sourceLineStart: 4,
      sourceLineEnd: 4,
      type: 'free_response',
    },
    analysis: {
      confidenceScore: 0.76,
      processedAt: new Date().toISOString(),
    },
  },
  {
    problemId: 'S2_P2',
    documentId: 'doc_seed_001',
    subject: 'Science',
    sectionId: 'S2',
    content: 'A student designed an experiment to determine the effect of pH on enzyme activity. What is the independent variable?',
    cognitive: {
      bloomsLevel: 'Remember',
      bloomsConfidence: 0.91,
      bloomsReasoning: 'Simple recall of experimental design terminology',
      bloomsContextDependent: false,
      complexityLevel: 1,
      estimatedTimeMinutes: 1.5,
      timeBreakdown: {
        readingMinutes: 0.3,
        comprehensionMinutes: 0.4,
        computationMinutes: 0.0,
        reasoningMinutes: 0.6,
        writingMinutes: 0.2,
      },
      linguisticComplexity: 0.35,
      reasoningStepsRequired: 1,
      proceduralWeight: 0.0,
      noveltyScore: 0.1,
      estimatedGradeLevel: 8,
    },
    classification: {
      problemType: 'multiple_choice',
      topics: ['experimental_design', 'enzyme_activity', 'biology'],
      requiresCalculator: false,
      requiresInterpretation: false,
      keywords: ['experiment', 'variables', 'science'],
    },
    structure: {
      isSubpart: false,
      numberingStyle: '1.',
      multiPartCount: 0,
      sourceLineStart: 5,
      sourceLineEnd: 5,
      type: 'multiple_choice',
    },
    analysis: {
      confidenceScore: 0.88,
      processedAt: new Date().toISOString(),
    },
  },
  {
    problemId: 'S3_P1',
    documentId: 'doc_seed_001',
    subject: 'English',
    sectionId: 'S3',
    content: 'Analyze how Shakespeare uses metaphor in Sonnet 18',
    cognitive: {
      bloomsLevel: 'Analyze',
      bloomsConfidence: 0.79,
      bloomsReasoning: 'Requires breaking down literary techniques and their effects',
      bloomsContextDependent: true,
      complexityLevel: 4,
      estimatedTimeMinutes: 6.0,
      timeBreakdown: {
        readingMinutes: 0.5,
        comprehensionMinutes: 1.5,
        computationMinutes: 0.0,
        reasoningMinutes: 3.0,
        writingMinutes: 1.0,
      },
      linguisticComplexity: 0.75,
      reasoningStepsRequired: 5,
      proceduralWeight: 0.0,
      noveltyScore: 0.6,
      estimatedGradeLevel: 11,
    },
    classification: {
      problemType: 'literary_analysis',
      topics: ['shakespeare', 'poetry', 'metaphor', 'literature'],
      requiresCalculator: false,
      requiresInterpretation: true,
      keywords: ['literature', 'analysis', 'poetry'],
    },
    structure: {
      isSubpart: false,
      numberingStyle: '1.',
      multiPartCount: 0,
      sourceLineStart: 6,
      sourceLineEnd: 6,
      type: 'free_response',
    },
    analysis: {
      confidenceScore: 0.71,
      processedAt: new Date().toISOString(),
    },
  },
  {
    problemId: 'S3_P2',
    documentId: 'doc_seed_001',
    subject: 'English',
    sectionId: 'S3',
    content: 'What is the main theme of the novel "To Kill a Mockingbird"?',
    cognitive: {
      bloomsLevel: 'Understand',
      bloomsConfidence: 0.87,
      bloomsReasoning: 'Requires identification and description of central theme',
      bloomsContextDependent: true,
      complexityLevel: 2,
      estimatedTimeMinutes: 3.5,
      timeBreakdown: {
        readingMinutes: 0.3,
        comprehensionMinutes: 0.8,
        computationMinutes: 0.0,
        reasoningMinutes: 1.5,
        writingMinutes: 0.9,
      },
      linguisticComplexity: 0.58,
      reasoningStepsRequired: 2,
      proceduralWeight: 0.0,
      noveltyScore: 0.2,
      estimatedGradeLevel: 9,
    },
    classification: {
      problemType: 'theme_identification',
      topics: ['mockingbird', 'literature', 'classic_novels'],
      requiresCalculator: false,
      requiresInterpretation: true,
      keywords: ['literature', 'theme', 'novel'],
    },
    structure: {
      isSubpart: false,
      numberingStyle: '1.',
      multiPartCount: 0,
      sourceLineStart: 7,
      sourceLineEnd: 7,
      type: 'short_answer',
    },
    analysis: {
      confidenceScore: 0.81,
      processedAt: new Date().toISOString(),
    },
  },
];

export interface ProblemPerformanceData {
  success_rate: number; // 0-100
  average_time_seconds: number;
  attempt_count: number;
  feedback_count: number;
  last_attempted: string;
}

export const SEED_PERFORMANCE: Record<string, ProblemPerformanceData> = {
  'S1_P1': { success_rate: 92, average_time_seconds: 68, attempt_count: 47, feedback_count: 12, last_attempted: '2026-02-10' },
  'S1_P2': { success_rate: 78, average_time_seconds: 145, attempt_count: 34, feedback_count: 18, last_attempted: '2026-02-09' },
  'S1_P3': { success_rate: 65, average_time_seconds: 198, attempt_count: 28, feedback_count: 22, last_attempted: '2026-02-08' },
  'S2_P1': { success_rate: 72, average_time_seconds: 256, attempt_count: 19, feedback_count: 14, last_attempted: '2026-02-07' },
  'S2_P2': { success_rate: 88, average_time_seconds: 92, attempt_count: 42, feedback_count: 9, last_attempted: '2026-02-10' },
  'S3_P1': { success_rate: 58, average_time_seconds: 385, attempt_count: 15, feedback_count: 25, last_attempted: '2026-02-06' },
  'S3_P2': { success_rate: 81, average_time_seconds: 218, attempt_count: 31, feedback_count: 11, last_attempted: '2026-02-09' },
};
