import React, { useState } from 'react';
import { RubricCriterion, GeneratedRubric } from '../../agents/analysis/types';
import { suggestRubricImprovements } from '../../agents/analysis/generateRubric';

interface RubricBuilderProps {
  rubric: GeneratedRubric;
  bloomDistribution: Record<string, number>;
  onRubricUpdate: (rubric: GeneratedRubric) => void;
}

export function RubricBuilder({
  rubric,
  bloomDistribution,
  onRubricUpdate,
}: RubricBuilderProps) {
  const [criteria, setCriteria] = useState<RubricCriterion[]>(rubric.criteria);
  const [editingId, setEditingId] = useState<string | null>(null);

  const suggestions = suggestRubricImprovements(criteria, bloomDistribution);
  const totalPoints = criteria.reduce((sum, c) => sum + c.maxPoints, 0);

  const handleUpdateCriterion = (id: string, field: string, value: string | number) => {
    setCriteria(criteria.map(c => {
      if (c.id === id) {
        return { ...c, [field]: value };
      }
      return c;
    }));
  };

  const handleAddCriterion = () => {
    const newCriterion: RubricCriterion = {
      id: `criterion-${Date.now()}`,
      name: 'New Criterion',
      description: 'Describe this criterion',
      maxPoints: 10,
      bloomLevels: ['Understand'],
    };
    setCriteria([...criteria, newCriterion]);
  };

  const handleRemoveCriterion = (id: string) => {
    if (criteria.length > 1) {
      setCriteria(criteria.filter(c => c.id !== id));
    }
  };

  const handleSave = () => {
    onRubricUpdate({
      criteria,
      totalPoints,
      isAutoGenerated: rubric.isAutoGenerated,
    });
    alert('Rubric updated successfully!');
  };

  const panelStyle: React.CSSProperties = {
    padding: '20px',
    backgroundColor: 'white',
    borderRadius: '8px',
    border: '1px solid #ddd',
    marginBottom: '20px',
  };

  const headerStyle: React.CSSProperties = {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '16px',
    paddingBottom: '12px',
    borderBottom: '2px solid #ddd',
  };

  const summaryStyle: React.CSSProperties = {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))',
    gap: '12px',
    marginBottom: '16px',
  };

  const summaryCardStyle: React.CSSProperties = {
    backgroundColor: '#f5f5f5',
    padding: '12px',
    borderRadius: '4px',
    textAlign: 'center',
    fontSize: '13px',
  };

  const summaryValueStyle: React.CSSProperties = {
    fontSize: '24px',
    fontWeight: 'bold',
    color: '#333',
    margin: '4px 0 0 0',
  };

  const criterionItemStyle: React.CSSProperties = {
    backgroundColor: '#f9f9f9',
    border: '1px solid #e0e0e0',
    borderRadius: '6px',
    padding: '12px',
    marginBottom: '12px',
  };

  const bloomBadgeStyle = (bloomLevel: string): React.CSSProperties => {
    const colors: Record<string, string> = {
      Remember: '#e3f2fd',
      Understand: '#bbdefb',
      Apply: '#90caf9',
      Analyze: '#42a5f5',
      Evaluate: '#2196f3',
      Create: '#1565c0',
    };

    return {
      display: 'inline-block',
      backgroundColor: colors[bloomLevel] || '#e0e0e0',
      color: '#333',
      padding: '2px 8px',
      borderRadius: '3px',
      fontSize: '11px',
      marginRight: '4px',
      marginBottom: '4px',
    };
  };

  const inputStyle: React.CSSProperties = {
    width: '100%',
    padding: '8px',
    borderRadius: '4px',
    border: '1px solid #ddd',
    fontSize: '13px',
    fontFamily: 'Arial, sans-serif',
    boxSizing: 'border-box',
    marginBottom: '8px',
  };

  const buttonStyle: React.CSSProperties = {
    padding: '8px 12px',
    borderRadius: '4px',
    border: 'none',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: '500',
  };

  const primaryButtonStyle: React.CSSProperties = {
    ...buttonStyle,
    backgroundColor: '#2196f3',
    color: 'white',
  };

  const deleteButtonStyle: React.CSSProperties = {
    ...buttonStyle,
    backgroundColor: '#f44336',
    color: 'white',
    padding: '4px 8px',
    fontSize: '12px',
  };

  const warningStyle: React.CSSProperties = {
    backgroundColor: '#fff3e0',
    border: '1px solid #ff9800',
    borderRadius: '6px',
    padding: '12px',
    marginBottom: '16px',
  };

  return (
    <div style={panelStyle}>
      <div style={headerStyle}>
        <h2 style={{ margin: 0 }}>⭐ Rubric Builder</h2>
        <span style={{ fontSize: '12px', color: '#999' }}>
          {rubric.isAutoGenerated ? '🤖 Auto-generated' : '✏️ Custom'}
        </span>
      </div>

      {/* Summary */}
      <div style={summaryStyle}>
        <div style={summaryCardStyle}>
          <div>Criteria</div>
          <p style={summaryValueStyle}>{criteria.length}</p>
        </div>
        <div style={summaryCardStyle}>
          <div>Total Points</div>
          <p style={summaryValueStyle}>{totalPoints}</p>
        </div>
        <div style={summaryCardStyle}>
          <div>Avg Points</div>
          <p style={summaryValueStyle}>{Math.ceil(totalPoints / criteria.length)}</p>
        </div>
      </div>

      {/* Suggestions */}
      {suggestions.length > 0 && (
        <div style={warningStyle}>
          <h4 style={{ margin: '0 0 8px 0', color: '#f57c00' }}>💡 Suggestions for Improvement</h4>
          <ul style={{ margin: 0, paddingLeft: '20px', fontSize: '13px', color: '#666' }}>
            {suggestions.map((suggestion, idx) => (
              <li key={idx} style={{ marginBottom: '4px' }}>
                {suggestion}
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Criteria List */}
      <div>
        <h3 style={{ margin: '16px 0 12px 0' }}>Criteria</h3>

        {criteria.map(criterion => (
          <div key={criterion.id} style={criterionItemStyle}>
            {editingId === criterion.id ? (
              // Edit Mode
              <div>
                <label style={{ fontSize: '12px', fontWeight: '600', color: '#333' }}>Criterion Name</label>
                <input
                  type="text"
                  value={criterion.name}
                  onChange={(e) => handleUpdateCriterion(criterion.id, 'name', e.target.value)}
                  style={inputStyle}
                  placeholder="e.g., Understanding of Concepts"
                />

                <label style={{ fontSize: '12px', fontWeight: '600', color: '#333' }}>Description</label>
                <textarea
                  value={criterion.description}
                  onChange={(e) => handleUpdateCriterion(criterion.id, 'description', e.target.value)}
                  style={{ ...inputStyle, height: '80px' }}
                  placeholder="Describe what quality work looks like for this criterion"
                />

                <label style={{ fontSize: '12px', fontWeight: '600', color: '#333' }}>Max Points</label>
                <input
                  type="number"
                  value={criterion.maxPoints}
                  onChange={(e) => handleUpdateCriterion(criterion.id, 'maxPoints', parseInt(e.target.value))}
                  style={inputStyle}
                  min="1"
                  max="100"
                />

                <div style={{ display: 'flex', gap: '8px' }}>
                  <button
                    onClick={() => setEditingId(null)}
                    style={{ ...primaryButtonStyle, flex: 1 }}
                  >
                    Save
                  </button>
                  <button
                    onClick={() => handleRemoveCriterion(criterion.id)}
                    style={deleteButtonStyle}
                  >
                    Delete
                  </button>
                </div>
              </div>
            ) : (
              // Display Mode
              <div onClick={() => setEditingId(criterion.id)} style={{ cursor: 'pointer' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                  <div style={{ flex: 1 }}>
                    <h4 style={{ margin: '0 0 6px 0', color: '#333' }}>{criterion.name}</h4>
                    <p style={{ margin: '0 0 8px 0', fontSize: '13px', color: '#666', lineHeight: '1.4' }}>
                      {criterion.description}
                    </p>
                    <div>
                      {criterion.bloomLevels.map((level, idx) => (
                        <span key={idx} style={bloomBadgeStyle(level)}>
                          {level}
                        </span>
                      ))}
                    </div>
                  </div>
                  <div style={{ textAlign: 'right', marginLeft: '12px' }}>
                    <p style={{ margin: '0 0 6px 0', fontSize: '18px', fontWeight: 'bold', color: '#2196f3' }}>
                      {criterion.maxPoints}
                    </p>
                    <p style={{ margin: 0, fontSize: '11px', color: '#999' }}>points</p>
                  </div>
                </div>
              </div>
            )}
          </div>
        ))}

        {/* Add New Criterion */}
        <button
          onClick={handleAddCriterion}
          style={{
            ...primaryButtonStyle,
            width: '100%',
            marginTop: '12px',
          }}
        >
          + Add Criterion
        </button>
      </div>

      {/* Save Button */}
      <button
        onClick={handleSave}
        style={{
          ...primaryButtonStyle,
          width: '100%',
          marginTop: '16px',
          padding: '12px',
          fontSize: '14px',
          fontWeight: '600',
        }}
      >
        💾 Save Rubric
      </button>
    </div>
  );
}
