/**
 * Dockyard Writer Output Component
 *
 * Displays the raw AI-generated assignment before atomization/canonicalization.
 * Teachers can review what the Writer generated and decide to:
 * 1. Continue to Foundry for canonicalization
 * 2. Edit and regenerate
 * 3. Try a different intent
 *
 * This is the first opportunity for teachers to see raw AI output.
 */

import React, { useState } from 'react';
import './DockwardWriterOutput.css';

interface DockwardWriterOutputProps {
  /** Raw text generated by the Writer */
  generatedText: string;
  
  /** Title/topic of the assignment */
  title?: string;
  
  /** Is the system currently regenerating? */
  isRegenerating?: boolean;
  
  /** Called when teacher wants to proceed to Foundry */
  onContinue: () => void;
  
  /** Called when teacher wants to regenerate with different parameters */
  onRegenerate?: () => void;
  
  /** Called when teacher wants to go back and try different intent */
  onBack?: () => void;
}

export function DockwardWriterOutput({
  generatedText,
  title,
  isRegenerating = false,
  onContinue,
  onRegenerate,
  onBack,
}: DockwardWriterOutputProps) {
  const [showFormatted, setShowFormatted] = useState(true);
  const [copiedToClipboard, setCopiedToClipboard] = useState(false);

  const handleCopyToClipboard = () => {
    navigator.clipboard.writeText(generatedText);
    setCopiedToClipboard(true);
    setTimeout(() => setCopiedToClipboard(false), 2000);
  };

  const wordCount = generatedText.trim().split(/\s+/).length;
  const problemCount = (generatedText.match(/Question|Problem|\d\./gi) || []).length;

  return (
    <div className="dockyard-writer-output">
      <div className="dwr-header">
        <div className="dwr-header-title">
          <h2>🚀 Dockyard Writer: Assignment Generated</h2>
          <p className="dwr-subtitle">
            Review the raw assignment below. The Writer created this content based on your mission parameters.
          </p>
        </div>
      </div>

      {/* Stats Bar */}
      <div className="dwr-stats">
        <div className="dwr-stat">
          <span className="stat-label">📄 Word Count</span>
          <span className="stat-value">{wordCount}</span>
        </div>
        <div className="dwr-stat">
          <span className="stat-label">📋 Estimated Problems</span>
          <span className="stat-value">{Math.max(problemCount, 1)}</span>
        </div>
        <div className="dwr-stat">
          <span className="stat-label">✨ Generated By</span>
          <span className="stat-value">Writer (Gemini)</span>
        </div>
      </div>

      {/* Document Preview */}
      <div className="dwr-preview-container">
        <div className="dwr-preview-controls">
          <label>
            <input
              type="checkbox"
              checked={showFormatted}
              onChange={(e) => setShowFormatted(e.target.checked)}
            />
            Formatted view
          </label>
          <button
            className="dwr-copy-btn"
            onClick={handleCopyToClipboard}
            title="Copy raw text to clipboard"
          >
            {copiedToClipboard ? '✓ Copied!' : '📋 Copy text'}
          </button>
        </div>

        <div
          className={`dwr-preview ${showFormatted ? 'formatted' : 'raw'}`}
          style={{
            padding: '24px',
            backgroundColor: '#fafafa',
            border: '1px solid #e0e0e0',
            borderRadius: '8px',
            minHeight: '300px',
            maxHeight: '600px',
            overflowY: 'auto',
            fontFamily: showFormatted ? 'Georgia, serif' : 'monospace',
            lineHeight: '1.7',
            color: '#333',
            whiteSpace: showFormatted ? 'normal' : 'pre-wrap',
            wordWrap: 'break-word',
          }}
        >
          {generatedText}
        </div>
      </div>

      {/* Review Notes */}
      <div className="dwr-review-notes" style={{
        backgroundColor: '#f0f8ff',
        border: '1px solid #b3d9ff',
        borderRadius: '8px',
        padding: '16px',
        marginBottom: '20px',
        fontSize: '14px',
        color: '#004085',
      }}>
        <h4 style={{ marginTop: 0, marginBottom: '8px' }}>🔍 Before You Proceed</h4>
        <ul style={{ marginBottom: 0, paddingLeft: '20px' }}>
          <li>Review the overall structure and content</li>
          <li>Check if the difficulty level matches your expectations</li>
          <li>Verify coverage of your learning objectives</li>
          <li>Next step: The system will atomize this into individual problems and tag them with Bloom's levels</li>
        </ul>
      </div>

      {/* Action Buttons */}
      <div className="dwr-actions">
        <button
          onClick={onContinue}
          disabled={isRegenerating}
          className="dwr-btn dwr-btn-primary"
          title="Proceed to Foundry for canonicalization"
        >
          ✓ Continue to Foundry
        </button>

        {onRegenerate && (
          <button
            onClick={onRegenerate}
            disabled={isRegenerating}
            className="dwr-btn dwr-btn-secondary"
            title="Regenerate with different parameters"
          >
            {isRegenerating ? '🔄 Regenerating...' : '🔄 Regenerate'}
          </button>
        )}

        {onBack && (
          <button
            onClick={onBack}
            disabled={isRegenerating}
            className="dwr-btn dwr-btn-tertiary"
            title="Go back to mission setup"
          >
            ← Back to Setup
          </button>
        )}
      </div>

      {isRegenerating && (
        <div className="dwr-loading-overlay">
          <div className="dwr-loading">
            <div className="spinner"></div>
            <p>Writer is generating your assignment...</p>
          </div>
        </div>
      )}
    </div>
  );
}
