import { useMemo, useState } from "react";

import type { RewriteResponse } from "../../types/rewrite";
import { diffHtml } from "../../utils/computeDiff";
import { DocumentStatusBadge } from "./DocumentStatusBadge";

type RewrittenSection = {
	sectionId: string;
	rewrittenText: string;
	original?: string;
};

type LegacyItem = {
	itemNumber: number;
	rewrittenStem: string;
	original?: string;
	/** Human-readable rationale generated by the LLM (spec F). */
	reason?: string;
	diffHtml?: string;
	/** Which student profile this rewrite is most intended to help. */
	profileHelped?: string;
	/** Which misconception this rewrite specifically targets. */
	misconceptionReduced?: string;
};

type LegacyRewrittenItem = {
	originalItemNumber: number;
	rewrittenStem: string;
	original?: string;
	reason?: string;
	diffHtml?: string;
	profileHelped?: string;
	misconceptionReduced?: string;
};

type ViewerRewrite = RewriteResponse & {
	docType?: "problem" | "notes" | "mixed";
	sections?: RewrittenSection[];
	items?: LegacyItem[];
	rewrittenItems?: LegacyRewrittenItem[];
	testLevel?: string[];
};

type Props = {
	rewrite: ViewerRewrite;
	documentId?: string | null;
};

// ---------------------------------------------------------------------------
// Diff display helper
// ---------------------------------------------------------------------------

/**
 * Render an inline word-level diff between `original` and `rewritten`.
 * Falls back to plain rewritten text when `original` is absent.
 */
function ItemDiff({ original, rewritten, precomputed }: { original?: string; rewritten: string; precomputed?: string }) {
	const [expanded, setExpanded] = useState(false);

	if (!original) {
		return <p style={{ margin: 0, lineHeight: 1.65 }}>{rewritten}</p>;
	}

	const html = precomputed ?? diffHtml(original, rewritten);
	if (!html) {
		return <p style={{ margin: 0, lineHeight: 1.65, color: "var(--v4-muted)" }}>(no changes)</p>;
	}

	return (
		<div>
			<button
				type="button"
				onClick={() => setExpanded((v) => !v)}
				style={{
					background: "none",
					border: "none",
					padding: "0 0 0.35rem",
					cursor: "pointer",
					fontSize: "0.75rem",
					color: "#4f6cf6",
					fontWeight: 600,
				}}
			>
				{expanded ? "▲ Hide diff" : "▼ Show diff"}
			</button>
			{expanded && (
				<div
					style={{
						margin: "0.25rem 0 0",
						lineHeight: 1.7,
						fontSize: "0.88rem",
						padding: "0.5rem 0.75rem",
						borderRadius: "8px",
						background: "rgba(248,250,255,0.9)",
						border: "1px solid rgba(79,108,246,0.12)",
					}}
					// eslint-disable-next-line react/no-danger
					dangerouslySetInnerHTML={{ __html: html }}
				/>
			)}
			<style>{`
				.diff-added  { background: #d1fae5; color: #065f46; border-radius: 2px; padding: 0 1px; }
				.diff-removed { background: #fee2e2; color: #991b1b; border-radius: 2px; padding: 0 1px; text-decoration: line-through; }
			`}</style>
		</div>
	);
}

function detectDocType(rewrite: ViewerRewrite): "problem" | "notes" | "mixed" {
	if (rewrite.docType) return rewrite.docType;
	const hasSections = (rewrite.sections?.length ?? 0) > 0;
	const hasItems = (rewrite.items?.length ?? 0) > 0 || (rewrite.rewrittenItems?.length ?? 0) > 0;
	if (hasSections && hasItems) return "mixed";
	if (hasSections) return "notes";
	return "problem";
}

export function RewriteViewer({ rewrite, documentId = null }: Props) {
	const docType = detectDocType(rewrite);
	const [localSections, setLocalSections] = useState<RewrittenSection[]>(rewrite.sections ?? []);

	const normalizedItems = useMemo(() => {
		if (rewrite.items && rewrite.items.length > 0) return rewrite.items;
		if (rewrite.rewrittenItems && rewrite.rewrittenItems.length > 0) {
			return rewrite.rewrittenItems.map((item) => ({
			itemNumber: item.originalItemNumber,
			rewrittenStem: item.rewrittenStem,
			original: item.original,
			reason: item.reason,
			profileHelped: item.profileHelped,
			misconceptionReduced: item.misconceptionReduced,
			}));
		}
		return []; // <-- THIS prevents the crash
		}, [rewrite.items, rewrite.rewrittenItems]);


	function updateSection(sectionId: string, rewrittenText: string) {
		setLocalSections((current) => current.map((section) => (
			section.sectionId === sectionId ? { ...section, rewrittenText } : section
		)));
	}

	return (
		<div style={{ marginTop: "1.25rem", fontSize: "0.95rem" }}>
			<p className="v4-kicker" style={{ marginBottom: "0.75rem" }}>
				Rewrite Preview ({docType})
			</p>
			{documentId ? <DocumentStatusBadge documentId={documentId} /> : null}

			{(docType === "notes" || docType === "mixed") && localSections.length > 0 ? (
				<div style={{ marginBottom: "1rem" }}>
					<h4 style={{ margin: "0 0 0.5rem" }}>Sections</h4>
					{localSections.map((section) => (
						<div
							key={section.sectionId}
							style={{
								background: "rgba(255,251,245,0.9)",
								border: "1px solid rgba(86,57,32,0.14)",
								borderRadius: "14px",
								padding: "1rem 1.25rem",
								marginBottom: "0.75rem",
							}}
						>
							<p style={{ margin: "0 0 0.45rem", fontWeight: 700, fontSize: "0.82rem", color: "#563920" }}>
								Section {section.sectionId}
							</p>
							<textarea
								value={section.rewrittenText}
								onChange={(event) => updateSection(section.sectionId, event.target.value)}
								rows={4}
								style={{
									width: "100%",
									padding: "0.6rem",
									borderRadius: "10px",
									border: "1px solid rgba(86,57,32,0.2)",
									background: "rgba(255,251,245,0.7)",
									fontFamily: "inherit",
									fontSize: "0.88rem",
									lineHeight: 1.5,
								}}
							/>
						</div>
					))}
				</div>
			) : null}

			{(docType === "problem" || docType === "mixed") && normalizedItems.length > 0 ? (
				<div style={{ marginBottom: "1rem" }}>
					<h4 style={{ margin: "0 0 0.5rem" }}>Items</h4>
					{normalizedItems.map((item) => (
						<div
							key={item.itemNumber}
							style={{
								background: "rgba(255,251,245,0.9)",
								border: "1px solid rgba(86,57,32,0.14)",
								borderRadius: "14px",
								padding: "1rem 1.25rem",
								marginBottom: "0.75rem",
							}}
						>
							<p style={{ margin: "0 0 0.35rem", fontWeight: 700, fontSize: "0.82rem", color: "#563920" }}>
								Item {item.itemNumber}
								{item.original && (
									<span style={{ marginLeft: "0.5rem", fontWeight: 400, color: "#4f6cf6" }}>★ changed</span>
								)}
							</p>
							<p style={{ margin: "0 0 0.35rem", lineHeight: 1.65 }}>{item.rewrittenStem}</p>
							<ItemDiff
								original={item.original}
								rewritten={item.rewrittenStem}
								precomputed={item.diffHtml}
							/>
							{item.reason && (
								<p
									style={{
										margin: "0.5rem 0 0",
										fontSize: "0.78rem",
										color: "#065f46",
										background: "rgba(209,250,229,0.4)",
										borderRadius: "6px",
										padding: "0.3rem 0.5rem",
									}}
								>
									<strong>Why this changed: </strong>
									{item.reason}
								</p>
							)}
							{item.profileHelped && (
								<p
									style={{
										margin: "0.4rem 0 0",
										fontSize: "0.75rem",
										color: "#1e3a5f",
										background: "rgba(219,234,254,0.5)",
										borderRadius: "6px",
										padding: "0.25rem 0.5rem",
									}}
								>
									<strong>Helps: </strong>
									{item.profileHelped}
								</p>
							)}
							{item.misconceptionReduced && (
								<p
									style={{
										margin: "0.4rem 0 0",
										fontSize: "0.75rem",
										color: "#78350f",
										background: "rgba(254,243,199,0.5)",
										borderRadius: "6px",
										padding: "0.25rem 0.5rem",
									}}
								>
									<strong>Addresses: </strong>
									{item.misconceptionReduced}
								</p>
							)}
						</div>
					))}
				</div>
			) : null}

			{normalizedItems.length === 0 && localSections.length === 0 && typeof rewrite.rewritten === "string" ? (
				<div
					style={{
						background: "rgba(255,251,245,0.9)",
						border: "1px solid rgba(86,57,32,0.14)",
						borderRadius: "14px",
						padding: "1rem 1.25rem",
						marginBottom: "0.75rem",
					}}
				>
					<h4 style={{ margin: "0 0 0.5rem" }}>Rewritten Document</h4>
					<p style={{ margin: 0, lineHeight: 1.65, whiteSpace: "pre-wrap" }}>{rewrite.rewritten}</p>
				</div>
			) : null}

			{rewrite.testLevel && rewrite.testLevel.length > 0 ? (
				<div>
					<h4 style={{ margin: "0 0 0.5rem" }}>Test-Level Suggestions</h4>
					<ul style={{ margin: 0, paddingLeft: "1.2rem" }}>
						{rewrite.testLevel.map((entry, index) => <li key={`${entry}-${index}`}>{entry}</li>)}
					</ul>
				</div>
			) : null}
		</div>
	);
}
