/**
 * Problem Validation Types (Phase 4)
 *
 * Defines the contract that all AI-generated problems must satisfy.
 * Each problem MUST have required metadata with values in specified ranges.
 */

import { BloomLevel, BloomDistribution } from './assessmentIntent';

// Re-export for convenience
export type { BloomLevel, BloomDistribution };

/**
 * Problem type classification
 */
export type ProblemType = 'multiple-choice' | 'true-false' | 'short-answer' | 'essay' | 'matching';

/**
 * Difficulty rating (1-5 scale)
 */
export type DifficultyRating = 1 | 2 | 3 | 4 | 5;

/**
 * A single problem with all required metadata
 * Generated by AI Writer
 */
export interface GeneratedProblem {
  // Required identifiers
  ProblemId: string;
  SequenceIndex: number; // 0, 1, 2, ..., N-1

  // Required pedagogical metadata
  BloomLevel: BloomLevel; // Must be one of 6 levels
  LinguisticComplexity: number; // 0.0–1.0 (constraint: 0.1–0.9)
  Difficulty: DifficultyRating; // Must be 1, 2, 3, 4, or 5

  // Required timing
  EstimatedTimeMinutes: number; // Must be > 0 (positive integer)

  // Required classification
  Type: ProblemType;

  // Required content
  Content: string; // The problem statement

  // Optional fields (backward compatible)
  Tags?: string[];
  Explanation?: string;
  AnswerKey?: string;
  Rubric?: string;
  NoveltyScore?: number;
  SimilarityToPrevious?: number;
}

/**
 * Validation error with problem context
 */
export interface ValidationError {
  problemId: string;
  problemIndex: number;
  field: string;
  value: any;
  constraint: string;
  message: string;
}

/**
 * Result of validating a single problem
 */
export interface ProblemValidationResult {
  valid: boolean;
  problemId: string;
  problemIndex: number;
  errors: ValidationError[];
}

/**
 * Result of validating an entire batch of problems
 */
export interface ProblemsValidationResult {
  valid: boolean;
  totalProblems: number;
  validProblems: number;
  invalidProblems: number;
  details: ProblemValidationResult[];
  batchErrors: BatchValidationError[];
}

/**
 * Batch-level validation errors
 * (not tied to a specific problem)
 */
export interface BatchValidationError {
  type:
    | 'SEQUENCE_INDEX_NOT_CONTIGUOUS'
    | 'TOTAL_TIME_OUT_OF_RANGE'
    | 'BLOOM_DISTRIBUTION_MISMATCH'
    | 'PROBLEM_COUNT_MISMATCH';
  message: string;
  details: Record<string, any>;
}

/**
 * Configuration for problem validation
 */
export interface ProblemValidationConfig {
  // Time validation
  timeAllowancePercent: number; // e.g., 10 means ±10%
  minTime: number; // Minimum EstimatedTimeMinutes per problem
  maxTime: number; // Maximum EstimatedTimeMinutes per problem

  // Complexity validation
  minComplexity: number; // e.g., 0.1
  maxComplexity: number; // e.g., 0.9

  // Bloom distribution validation
  bloomTolerancePercent: number; // e.g., 5 means ±5%

  // Other
  requiredFields: string[]; // Fields that must be present
  difficultyRange: [number, number]; // [min, max], e.g. [1, 5]
}

/**
 * Target metrics for an assessment
 * Used to validate generated problems against teacher intent
 */
export interface AssessmentTargets {
  totalTimeMinutes: number;
  bloomTargets: Record<BloomLevel, number>; // Percentages, sum ≈ 1.0
  expectedQuestionCount: number;
  problemType?: ProblemType; // If all problems should be same type
}

/**
 * Summary statistics for a batch of problems
 */
export interface ProblembatchStatistics {
  totalProblems: number;
  totalTime: number;
  averageComplexity: number;
  bloomDistribution: Record<BloomLevel, number>;
  difficultyDistribution: Record<DifficultyRating, number>;
  typeDistribution: Record<ProblemType, number>;
  averageTimePerProblem: number;
}
