// Type definitions for assignment analysis system

export type BloomLevel = 'Remember' | 'Understand' | 'Apply' | 'Analyze' | 'Evaluate' | 'Create';

export interface PeerReviewComment {
  id: string;
  tags: string[];
  section: string;
  comment: string;
  suggestion: string;
  severity: 'low' | 'medium' | 'high';
}

export interface TagFrequencyEntry {
  tag: string;
  frequency: number;
  bloomLevels: BloomLevel[];
}

export interface AssignmentAnalysis {
  estimatedTimeMinutes: number;
  bloomDistribution: Record<BloomLevel, number>;
  tagFrequency: TagFrequencyEntry[];
  peerReviewComments: PeerReviewComment[];
  clarityScore: number; // 1-10
  completenessScore: number; // 1-10
  alignmentScore: number; // 1-10
  overallScore: number; // 1-10
}

export interface TeacherNote {
  id: string;
  tags: string[];
  section: string;
  originalText: string;
  suggestion: string;
  resolution: 'pending' | 'ai-resolved' | 'teacher-resolved';
  replacementText?: string;
  timestamp: string;
}

export interface StudentSimulation {
  id: string;
  persona: string;
  timeToCompleteMinutes: number;
  understood: string[];
  struggledWith: string[];
  confusionPoints: string[];
  checkedOutAt?: string;
  completedAt?: string;
  estimatedGrade: string;
  estimatedScore: number;
  dropoffReason?: string;
}

export interface RubricCriterion {
  id: string;
  name: string;
  description: string;
  maxPoints: number;
  bloomLevels: BloomLevel[];
}

export interface GeneratedRubric {
  criteria: RubricCriterion[];
  totalPoints: number;
  isAutoGenerated: boolean;
}

export interface AssignmentMetadataForAnalysis {
  title: string;
  content: string;
  learningObjectives: string[];
  estimatedTimeMinutes?: number;
  gradeLevel: number;
  bloomLevels?: BloomLevel[];
  rubric?: RubricCriterion[];
  extractedTags?: string[];
}
